// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {VmSafe} from "@forge-std/Vm.sol";

/// @notice Reads and writes the deployed addresses in `deployments/`, per chain and per user.
library Deployments {
    VmSafe private constant vm = VmSafe(address(uint160(uint256(keccak256("hevm cheat code")))));

    /// @notice The chain file does not exist.
    /// @param path The path looked up.
    error DeploymentsFileMissing(string path);

    /// @notice The key is not in the file.
    /// @param path The file path.
    /// @param key The key looked up.
    error DeploymentMissing(string path, string key);

    /// @notice A record entry has no `index` or `address`.
    /// @param path The file path.
    /// @param entry The index of the broken entry.
    error MalformedVaultsFile(string path, uint256 entry);

    /// @notice A key/address pair of the chain file.
    struct Record {
        string key;
        address addr;
    }

    string private constant ROOT = "deployments/";

    /// @notice Writes the protocol addresses to `deployments/<chainId>.json`.
    /// @param chainId The chain of the file.
    /// @param records The key/address pairs to write.
    function save(uint256 chainId, Record[] memory records) internal {
        vm.createDir(ROOT, true);

        string memory handle = string.concat("deployments.", vm.toString(chainId));

        string memory json;
        for (uint256 i = 0; i < records.length; i++) {
            json = vm.serializeAddress(handle, records[i].key, records[i].addr);
        }

        vm.writeJson(json, _protocolPath(chainId));
    }

    /// @notice Reads a protocol address, reverting if the file or the key does not exist.
    /// @param chainId The chain of the file.
    /// @param key The key of the address.
    /// @return The recorded address.
    function read(uint256 chainId, string memory key) internal view returns (address) {
        string memory path = _protocolPath(chainId);
        if (!vm.exists(path)) revert DeploymentsFileMissing(path);

        string memory json = vm.readFile(path);
        string memory pointer = string.concat(".", key);
        if (!vm.keyExistsJson(json, pointer)) revert DeploymentMissing(path, key);

        return vm.parseJsonAddress(json, pointer);
    }

    /// @notice Records the user's vault, replacing the entry with the same `index`.
    /// @param chainId The chain of the file.
    /// @param user The owner of the vault.
    /// @param index The index of the vault for this owner.
    /// @param vault The address of the vault.
    function saveVault(uint256 chainId, address user, uint256 index, address vault) internal {
        string memory dir = _userDir(chainId, user);
        vm.createDir(dir, true);

        (uint256[] memory indexes, address[] memory addresses) = vaultsOf(chainId, user);

        string memory list;
        bool replaced;

        for (uint256 i = 0; i < indexes.length; i++) {
            address entry = indexes[i] == index ? vault : addresses[i];
            if (indexes[i] == index) replaced = true;

            list = string.concat(list, i == 0 ? "" : ",", _entry(indexes[i], entry));
        }

        if (!replaced) {
            list = string.concat(list, indexes.length == 0 ? "" : ",", _entry(index, vault));
        }

        string memory doc = "{\"_comment\":\"Generated by the actions in script/user/. Records what was ";
        doc = string.concat(doc, "DEPLOYED, never what is configured: configuration is read from the vault.\",");

        vm.writeJson(string.concat(doc, "\"vaults\":[", list, "]}"), _vaultsPath(chainId, user));
    }

    /// @notice The user's already-recorded vaults; empty if there is no file yet.
    /// @param chainId The chain of the file.
    /// @param user The owner of the vaults.
    /// @return indexes The recorded indexes.
    /// @return addresses The addresses in the same order.
    function vaultsOf(uint256 chainId, address user)
        internal
        view
        returns (uint256[] memory indexes, address[] memory addresses)
    {
        string memory path = _vaultsPath(chainId, user);
        if (!vm.exists(path)) return (indexes, addresses);

        string memory json = vm.readFile(path);
        if (!vm.keyExistsJson(json, ".vaults")) return (indexes, addresses);

        uint256 count;
        while (vm.keyExistsJson(json, _at(count, "index"))) {
            count++;
        }

        if (vm.keyExistsJson(json, string.concat(".vaults[", vm.toString(count), "]"))) {
            revert MalformedVaultsFile(path, count);
        }

        indexes = new uint256[](count);
        addresses = new address[](count);

        for (uint256 i = 0; i < count; i++) {
            indexes[i] = vm.parseJsonUint(json, _at(i, "index"));
            addresses[i] = vm.parseJsonAddress(json, _at(i, "address"));
        }
    }

    function _at(uint256 i, string memory field) private pure returns (string memory) {
        return string.concat(".vaults[", vm.toString(i), "].", field);
    }

    function _protocolPath(uint256 chainId) private pure returns (string memory) {
        return string.concat(ROOT, vm.toString(chainId), ".json");
    }

    function _userDir(uint256 chainId, address user) private pure returns (string memory) {
        return string.concat(ROOT, "user/", vm.toString(chainId), "/", vm.toString(user), "/");
    }

    function _vaultsPath(uint256 chainId, address user) private pure returns (string memory) {
        return string.concat(_userDir(chainId, user), "vaults.json");
    }

    function _entry(uint256 index, address vault) private pure returns (string memory) {
        return string.concat("{\"index\":", vm.toString(index), ",\"address\":\"", vm.toString(vault), "\"}");
    }
}
